---

- name: Remove conflicting Debian Docker packages
  apt:
    name:
      - docker
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-plugin
      - docker-buildx
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg \
      | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present
    update_cache: yes
  notify: restart docker

- name: Install Docker Compose plugin
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes

- name: Verify Docker Compose installation
  command: docker compose version
  register: compose_version
  changed_when: false

- name: Show Docker Compose version
  debug:
    var: compose_version.stdout

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
