---
galaxy_info:
  author: Alexander Hammers
  description: Install and configure Docker
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
